title: Chinedu
description: Travel and family moments
url: "https://chinedu.ca"
baseurl: ""

author: Chinedu

markdown: kramdown
permalink: /blog/:title/
remote_theme: jekyll/minima

header_pages:
  - about.markdown
  - photos.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
